### ISSUE TITLE
[Kamal 2.0] Running accessory details can cause nomethoderror

### ISSUE THREAD

**Issue by bendangelo** [basecamp/kamal#1061]
I realized running this command on an accessory that isn't running or doesn't even exist:
`kamal accessory details spacy-server --verbose`

Will cause this error:
```
  ERROR (NoMethodError): undefined method `to_sentence' for an instance of Array
/home/bendangelo/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/kamal-2.1.1/lib/kamal/cli/accessory.rb:257:in `error_on_missing_accessory'
/home/bendangelo/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/kamal-2.1.1/lib/kamal/cli/accessory.rb:248:in `with_accessory'
/home/bendangelo/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/kamal-2.1.1/lib/kamal/cli/accessory.rb:107:in `details'
/home/bendangelo/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'

```

**Comment by nikhilbhatt** [comment]
This is because `to_sentence` method is part of rails active-support and is being used here in Line 257 below:
https://github.com/basecamp/kamal/blob/4b2c9cdc7257fa52bff743b308033118a2897c41/lib/kamal/cli/accessory.rb#L252-L258

@bendangelo I think If you run this command as part of your rails project you should not see this issue but IMO we should remove the use of `to_sentence` method altogether because it is dependent on rails.

May be we can replace this with `options.join(', ')`

**Comment by bendangelo** [comment]
I thought I was running this under rails. I'm on rails 8 beta.
