### ISSUE TITLE
load environment variables from multiple .env files as dotenv-rails

### ISSUE THREAD

**Issue by xiaohui-zhangxh** [basecamp/kamal#233]
Almost all of our projects are loading environment variables with dotenv-rails, so we always commit `.env` file to Git, our developers clone repository and create `.env.local` to override database/redis settings

I think mrsk can follow the best practice of dotenv-rails, not only read `.env` file, but also another files in priority as: 

1. .env.`[destination]`.local
2. .env.`[destination]`
3. .env.deploy.local
4. .env.local
5. .env.deploy
6. .env

**Comment by xiaohui-zhangxh** [comment]
I have implemented this feature https://github.com/mrsked/mrsk/compare/main...xiaohui-zhangxh:mrsk:feature/multiple-dotenv-files , if this feature is accepted I will write some tests and create a PR

**Comment by northeastprince** [comment]
Yeah, it feels wrong to have sensitive production credentials in `.env`.

**Comment by jasonfb** [comment]
I think I'm stuck/confused around this point too, especially the RAILS_MASTER_KEY. (see my issue https://github.com/mrsked/mrsk/issues/261)

what I don't understand is why would the implementation in MRSK be any different than the implementation in DotEnv? 

if MRSK has dotenv as a dependency, then it should follow the same patterns that dotenv use. Perhaps my RAILS_MASTER_KEY (defined in both `.env.productoin` and also in `config/master.key` — _neither of which is in source control_) isn't being picked up because MRSK doesn't know how to read from `.env.productoin`  ?

We aren't supposed to put credentials into source control, so there will need to be at least one file that contains the master key on local hard drive that isn't in git (source control).

But what's confusing is how many options there are: should that file be `config/master.key` or should it be `.env` file that isn't in Git? (I realize that you can use DotEnv without encrypted secrets, which supports flexibility)

From an ergonomics perspective, I'm not really a huge fan of 6(!) `.env` files at all— too confusing! And what's the difference between `.env.deploy` and `.env.deploy.local`?!? — too confusing!

I'd suggest we streamline towards just having as few places as possible to reduce the confusion. 

If you need a `.env.local` that overrides the other `.env` files that's a fine choice for a single developer to make, but I don't think we should encourage unnecessary proliferation of `.env` files. It's very confusing to work with and having to refer to a chart to determine the priority order of the loaded ENVs is annoying (I've seen the chart). 


I'm not saying to re-think DotEnv— it already has the chart and the priority order and all the different `.env` files (but it does NOT have any `.env.deploy.local` or `.env.deploy` — that's never something I've seen in any app or project ever, and only exists AFAIK on this Github issue) 


I guess what I'm looking for are **clear instructions** around this, like:

"If you are using encrypted secrets, you'll need your RAILS_MASTER_KEY available to your production environment. To do that, you can choose A or B"

don't give me a million choices, don't proliferate those choices into all matter of different `.env` files. 

If I go to the drug sure I want two choices of shampoo: The fancy stuff and the cheap stuff. I don't want 15 shampoos to choose from.

The choice overload explosion has to be carefully managed when building new tech like this because it will significantly determine how much friction people will have with the tech and that will determine how much adoption the tech will see.

**Comment by jasonfb** [comment]
I'd suggest "coding by config file" is an anti-pattern and that this `.env` stuff is bordering on antipattern territory. Rails encrypted secrets was supposed to make this more streamlined, but somehow it just feels like choice overload now.

**Comment by xiaohui-zhangxh** [comment]
> 

Yes, when/how should we use `.env` is a problem, years ago when I was using docker-compose, it load environment variables from .env, I have to change .env while running docker-compose, then rollback changes after it. 

Devspace has a good option to load `.env` file, https://www.devspace.sh/docs/configuration/variables#devspace_env_file-for-env-file-definition , maybe we can do it like this:

```yaml
# config/deploy.yml
dotenv: '.env'
# or
dotenv:
- '.env.deploy.local'
- '.env.deploy'
- '.env'
```

**Comment by jasonfb** [comment]
so the settings in `.deploy` only affect the deploy but don't stick in any actual environment? 
Just trying to understand why you would use a separate .env.deploy file when MRSK already has its own configuration file in `config/deploy.yml` 

Like, why not stick those (deploy-specific) settings into MRSK's `config/deploy.yml` instead of a special `.env` file? 

unless maybe you have some external reason, like for example, multiple mechanisms of deploy or you don't want to have MRSK as a dependency.

**Comment by xiaohui-zhangxh** [comment]
> so the settings in `.deploy` only affect the deploy but don't stick in any actual environment? Just trying to understand why you would use a separate .env.deploy file when MRSK already has its own configuration file in `config/deploy.yml`
> 
> Like, why not stick those (deploy-specific) settings into MRSK's `config/deploy.yml` instead of a special `.env` file?
> 
> unless maybe you have some external reason, like for example, multiple mechanisms of deploy or you don't want to have MRSK as a dependency.

Actually it's not about `.deploy` suffix, it's about `.local` suffix should override `.env` as `dotenv-rails`, then we can commit   `.env` file to Git instead of making a file `.env.example`. Deployer can just write some environment variables in `.env.local`.

For instance:

this `.env` comes from Git.

```env
# .env 

SEO_TITLE = "Welcome to world"
DB_PASSWORD =
```

Deployer is professional or project is well documented, he creates `.env.local` and just write some necessary variables for deployment.

```env
# .env.local
DB_PASSWORD = "foobar"
GIT_USERNAME = 'user1'
GIT_PASSWORD = 'pass1'
RAILS_MASTER_KEY = xxxxxx
```

Mostly, deployer actually is developer too, he frequently update code and commit it to Git, in order to keep the environment variables he has to check files carefully to prevent `.env` get into Git.

**Comment by cfarvidson** [comment]
I actually missed this issue and created https://github.com/mrsked/mrsk/discussions/288.

I totally agree with @xiaohui-zhangxh that the expected behavior (with the expected `.env` inheritance/precedence)  seems broken in `mrsk`.

Now It seems to support `.env` and that's fine if you don't use .env locally. Just the other day I almost deployed my local dev setup to the production environment. For my hobby project so that's not such a big deal but you get the point. 😊 

I'm not a rails developer so I don't really have an opinion on how to structure rails projects. But If the use of `.env` files is a good practice or not might be besides the point. It's a fairly common practice to use `.env` files.

**Comment by cfarvidson** [comment]
> Like, why not stick those (deploy-specific) settings into MRSK's `config/deploy.yml` instead of a special `.env` file?

@jasonfb I don't really understand how that would solve the issue of secrets like my local `DATABASE_URL` secret not colliding with the production one? 

Am I missing something 😊 ?

**Comment by cfarvidson** [comment]
I think I have created a workaround that works for me. It's a bit janky but it works.

1. Installed `dotenv` by running `gem install dotenv`. 
2. Added the `alias mrsk="dotenv -f .env.production.local mrsk"` to my `~/.zshrc` file.

Now I can have a separate `.env.local` for my local dev environment and another `.env.production.local` if I want to redeploy or interact with `mrsk` in my remote production environment.

I'm happy! 😃

**Comment by xiaohui-zhangxh** [comment]
Here is my thought, if we add an options to config/deploy.yml to make us load our favor env files, that would be happy to us, like this:

```yaml
# config/deploy.yml

dotenv:
- .env.local
- .env

# config/deploy.staging.yml

dotenv:
- .env.staging.local
- .env.staging
- .env
```

from here https://github.com/mrsked/mrsk/blob/main/lib/mrsk/cli/base.rb#L33 , we just check if there is a customized `dotenv`, otherwise load as default

what do you think? @dhh @jasonfb

**Comment by xiaohui-zhangxh** [comment]
> 

Oh, I found `load_envs` runs before `initialize_commander`, this is impossible to get customized `dotenv` from `load_envs`. 

Anyway, let's think about a solution start from here. create `.mrsk/config` like `.git` ?

**Comment by xiaohui-zhangxh** [comment]
Considering not all people like dotenv-rails style, so I think it's not necessary make kamal do any changes. for me, I just put this monky patch to `bin/kamal`

```ruby
# bin/kamal

# .....
require "rubygems"
require "bundler/setup"

require "kamal"
require 'kamal/cli/base'
Kamal::Cli::Base.class_eval do
  private

  def load_envs
    if destination = options[:destination]
      Dotenv.load(".env.#{destination}.deploy", ".env.#{destination}", ".env")
    else
      Dotenv.load(".env.deploy", ".env")
    end
  end
end

load Gem.bin_path("kamal", "kamal")
```
