### ISSUE TITLE
Changed service name, cleanup now fails on every build

### ISSUE THREAD

**Issue by olivermt** [basecamp/kamal#333]
Hello,

I changed a service name and now the mrsk deploy command fails on every execution with:

```
 DEBUG [1dc53147] Command: docker image ls --filter label=service=redacted --format '{{.ID}} {{.Repository}}:{{.Tag}}' | grep -v -w "$(docker container ls -a --format '{{.Image}}\|' --filter label=service=redacted | tr -d '\n')rg.nl-ams.scw.cloud/redacted-cr/redactedr:latest\|rg.nl-ams.scw.cloud/redacted-cr/redacted:<none>" | while read image tag; do docker rmi $tag; done
 DEBUG [1dc53147] 	Error response from daemon: conflict: unable to remove repository reference "rg.nl-ams.scw.cloud/redacted-cr/redacted
```

I think the key here is that somehow the state has ended up with the `:<none>` label.
`mrsk remove` did not clean up this bad state, is there another way to prune all data without wiping server?

**Comment by igor-alexandrov** [comment]
I tried changing the service name and deploying, but I didn't encounter the error you mentioned. However, after the deployment was complete, I noticed that two Rails containers were up and running. This appears to be the expected behavior, at least for now.

![Screenshot 2023-06-20 at 11 41 55](https://github.com/mrsked/mrsk/assets/100725/20bd059b-42b2-496e-b57e-c2ca5c1ad090)

**Comment by dhh** [comment]
Change back to what it was, run remove, then deploy from there.

**Comment by olivermt** [comment]
doesnt work, but I just cleaned the server instead of trying to figure this one out 🤷
