### ISSUE TITLE
Cloned a server from snapshot (Hetzner) and Bad Gateway (server.pid already exist)

### ISSUE THREAD

**Issue by silva96** [basecamp/kamal#664]
It's not an ideal situation where you have a server snapshot, spin up a new server and when you try to access it's IP it says "Bad Gateweay"

Logs show this:

`A server is already running (pid: 1, file: /rails/tmp/pids/server.pid).`

Doing a `kamal redeploy` fixes the problem

**Comment by ruyrocha** [comment]
This issue seems to be [solved on Rails](https://github.com/rails/rails/pull/49211) side.

However, it's possible to hook into [task responsible for starting containers](https://github.com/basecamp/kamal/blob/main/lib/kamal/cli/app.rb#L69-L81) to fix it by looking if there's a running process that matches the PID on file; if not, remove it, so Rails can boot up.

**Comment by acidtib** [comment]
you can handle this in the docker entrypoint

```
if [ -f tmp/pids/server.pid ]; then
  rm tmp/pids/server.pid
fi
```
