### ISSUE TITLE
Generated .env file requires environment variables in the `env` section in `deploy.yml`

### ISSUE THREAD

**Issue by voberoi** [basecamp/kamal#672]
Hi there,

I have three config files for Kamal:

- `config/deploy.yml`
- `config/deploy.production.yml`
- `.env.production.erb`

On deploy, I expected the generated `.env.production` file to be populated and copied over to my host.

The .env.production file was empty on the host. Generating the .env file locally with envify worked just fine, however.

I ended up getting this to work after listing the variable names I wanted in the `env` section of `deploy.production.yml` like so:

```
env:
  secret:
    - DATABASE_PASSWORD
    - ANOTHER_PASSWORD
    - ...
```

Only the values listed in that section end up on the host.  So now I have to:

- Update my `.env.production.erb`
- Update the `env` section in any `deploy.yml` files.

... in order to update my environment variables.

Is this intentional? If so:

- This would be great to add to the docs.
- Also want to request a change to this behavior because the DX is confusing.

If not -- would love to fix this.

Thanks!

**Comment by wenderjean** [comment]
In my perspective, it is expected to happen, @voberoi. Look, when you run envify, Kamal is going to process your template and grab the envs following the logic you put in the .erb file, like the 1Password and BitWarden examples in the docs. Actually, these envs are going to be loaded into your environment and used for validation purposes during the env push command. On the other hand, Kamal is going to upload to your hosts only those known variables declared in the configuration.

```
The flow follows these steps
1. "kamal envify" compiles the template and generates .env.production
2. "kamal env push" loads .env, validates if those variables present in configuration file are present in ENV
3. Uploads to hosts
```

Does that make sense?

**Comment by voberoi** [comment]
Your explanation makes sense to me. It sounds like this behavior intentional.

In what cases would a user update env.erb to add a secret but choose not to add it to deploy.yml as well so that it ends up on their hosts?

This behavior seems unexpected to me -- I'd say it at least warrants a note in the documentation.

**Comment by nickhammond** [comment]
@voberoi A new KAMAL_REGISTRY_PASSWORD, a secrets manager decryption key are examples don't usually end up in your deploy.yml. I like the manual push because it's very intentional when you want to change a value and it makes it more obvious to confirm you .env file values first. 

There's a small note about this on the docs site https://kamal-deploy.org/docs/configuration#using-env-variables

The template that is used now when you run `kamal init` also has this comment above the env section.

```
# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  secret:
```

**Comment by voberoi** [comment]
Love that change, thanks!

Closing this issue, since this is intentional + it's documented now.

**Comment by jeromedalbert** [comment]
One could argue that changing just one `.env.production.erb` file by itself can be very intentional, as changing any file with the word "production" in it should naturally make you extra careful.

FYI you can change the behavior and automate everything by doing something like this:

```yaml
env:
  secret:
    <%= Dotenv.parse('.env.production').keys - ['KAMAL_REGISTRY_PASSWORD'] %>
```

I don't know if I am doing a disservice by sharing this tip but I found it interesting. _[insert "your scientists were so preoccupied with whether or not they could, they didn’t stop to think if they should" meme here]_

**Comment by f16z** [comment]
Glad I found this, I was on an older version of kamal and when I upgraded, env vars stopped functioning. Had me going crazy thinking it was another different change I had made previously.

I wouldn't have expected to "Add a new env var, it must be added in two files" but @jeromedalbert suggestion shared above helps with this.
