### ISSUE TITLE
ERROR (Kamal::ConfigurationError): unknown keys

### ISSUE THREAD

**Issue by nnslvp** [basecamp/kamal#867]
<img width="714" alt="image" src="https://github.com/basecamp/kamal/assets/65916399/4337b87e-435c-4acc-a2ff-1fc78d9bb615">

<img width="540" alt="image" src="https://github.com/basecamp/kamal/assets/65916399/5e73aa4d-322b-4044-bce2-ae94582e2a92">

I think a case like this should be valid.

**Comment by zdehasek** [comment]
Yes I had a same issue

**Comment by ruyrocha** [comment]
Just to add a little bit of context, it seems that the anchors (`&`) and aliases (`*`) are a way to share common configuration settings across multiple services on the [Compose spec](https://github.com/compose-spec/compose-spec); it is an [extension](https://github.com/compose-spec/compose-spec/blob/main/spec.md#extension) when the key starts with `x-`, as node labels on screenshot above. 

It's raising the `ConfigurationError` [per this validation](https://github.com/basecamp/kamal/blob/main/lib/kamal/configuration/validator.rb#L18-L20), since the parsed configuration keys starting with `x-` are unknown to Kamal.

**Comment by djmb** [comment]
Oh nice idea @ruyrocha, we can add similar support to Kamal
